// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/landing_target_server/landing_target_server.proto)

#include "landing_target_server/landing_target_server.grpc.pb.h"
#include "plugins/landing_target_server/landing_target_server.h"

#include "mavsdk.h"

#include "lazy_server_plugin.h"

#include "log.h"
#include <atomic>
#include <cmath>
#include <future>
#include <limits>
#include <memory>
#include <sstream>
#include <vector>

namespace mavsdk {
namespace mavsdk_server {


template<typename LandingTargetServer = LandingTargetServer, typename LazyServerPlugin = LazyServerPlugin<LandingTargetServer>>

class LandingTargetServerServiceImpl final : public rpc::landing_target_server::LandingTargetServerService::Service {
public:

    LandingTargetServerServiceImpl(LazyServerPlugin& lazy_plugin) : _lazy_plugin(lazy_plugin) {}



    template<typename ResponseType>
    void fillResponseWithResult(ResponseType* response, mavsdk::LandingTargetServer::Result& result) const
    {
        auto rpc_result = translateToRpcResult(result);

        auto* rpc_landing_target_server_result = new rpc::landing_target_server::LandingTargetServerResult();
        rpc_landing_target_server_result->set_result(rpc_result);
        std::stringstream ss;
        ss << result;
        rpc_landing_target_server_result->set_result_str(ss.str());

        response->set_allocated_landing_target_server_result(rpc_landing_target_server_result);
    }




    static std::unique_ptr<rpc::landing_target_server::Position> translateToRpcPosition(const mavsdk::LandingTargetServer::Position &position)
    {
        auto rpc_obj = std::make_unique<rpc::landing_target_server::Position>();


            
        rpc_obj->set_x(position.x);
            
        
            
        rpc_obj->set_y(position.y);
            
        
            
        rpc_obj->set_z(position.z);
            
        

        return rpc_obj;
    }

    static mavsdk::LandingTargetServer::Position translateFromRpcPosition(const rpc::landing_target_server::Position& position)
    {
        mavsdk::LandingTargetServer::Position obj;


            
        obj.x = position.x();
            
        
            
        obj.y = position.y();
            
        
            
        obj.z = position.z();
            
        
        return obj;
    }




    static rpc::landing_target_server::LandingTargetResult::Result translateToRpcResult(const mavsdk::LandingTargetServer::Result& result)
    {
        switch (result) {
            default:
                LogErr() << "Unknown result enum value: " << static_cast<int>(result);
            // FALLTHROUGH
            case mavsdk::LandingTargetServer::Result::Unknown:
                return rpc::landing_target_server::LandingTargetResult_Result_RESULT_UNKNOWN;
            case mavsdk::LandingTargetServer::Result::Success:
                return rpc::landing_target_server::LandingTargetResult_Result_RESULT_SUCCESS;
            case mavsdk::LandingTargetServer::Result::NoSystem:
                return rpc::landing_target_server::LandingTargetResult_Result_RESULT_NO_SYSTEM;
        }
    }

    static mavsdk::LandingTargetServer::Result translateFromRpcResult(const rpc::landing_target_server::LandingTargetResult::Result result)
    {
        switch (result) {
            default:
                LogErr() << "Unknown result enum value: " << static_cast<int>(result);
            // FALLTHROUGH
            case rpc::landing_target_server::LandingTargetResult_Result_RESULT_UNKNOWN:
                return mavsdk::LandingTargetServer::Result::Unknown;
            case rpc::landing_target_server::LandingTargetResult_Result_RESULT_SUCCESS:
                return mavsdk::LandingTargetServer::Result::Success;
            case rpc::landing_target_server::LandingTargetResult_Result_RESULT_NO_SYSTEM:
                return mavsdk::LandingTargetServer::Result::NoSystem;
        }
    }




    grpc::Status PublishLandingTargetRelative(
        grpc::ServerContext* /* context */,
        const rpc::landing_target_server::PublishLandingTargetRelativeRequest* request,
        rpc::landing_target_server::PublishLandingTargetRelativeResponse* response) override
    {
        if (_lazy_plugin.maybe_plugin() == nullptr) {
            
            if (response != nullptr) {
                
                // For server plugins, this should never happen, they should always be constructible.
                auto result = mavsdk::LandingTargetServer::Result::Unknown;
                fillResponseWithResult(response, result);
            }
            
            return grpc::Status::OK;
        }

        if (request == nullptr) {
            LogWarn() << "PublishLandingTargetRelative sent with a null request! Ignoring...";
            return grpc::Status::OK;
        }
            
        
        auto result = _lazy_plugin.maybe_plugin()->publish_landing_target_relative(translateFromRpcPosition(request->position()));
        

        
        if (response != nullptr) {
            fillResponseWithResult(response, result);
        }
        

        return grpc::Status::OK;
    }


    void stop() {
        _stopped.store(true);
        for (auto& prom : _stream_stop_promises) {
            if (auto handle = prom.lock()) {
                handle->set_value();
            }
        }
    }

private:
    void register_stream_stop_promise(std::weak_ptr<std::promise<void>> prom) {
        // If we have already stopped, set promise immediately and don't add it to list.
        if (_stopped.load()) {
            if (auto handle = prom.lock()) {
                handle->set_value();
            }
        } else {
            _stream_stop_promises.push_back(prom);
        }
    }

    void unregister_stream_stop_promise(std::shared_ptr<std::promise<void>> prom) {
        for (auto it = _stream_stop_promises.begin(); it != _stream_stop_promises.end(); /* ++it */) {
            if (it->lock() == prom) {
                it = _stream_stop_promises.erase(it);
            } else {
                ++it;
            }
        }
    }


    LazyServerPlugin& _lazy_plugin;

    std::atomic<bool> _stopped{false};
    std::vector<std::weak_ptr<std::promise<void>>> _stream_stop_promises {};
};

} // namespace mavsdk_server
} // namespace mavsdk