// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/landing_target_server/landing_target_server.proto)

#include <iomanip>

#include "landing_target_server_impl.h"
#include "plugins/landing_target_server/landing_target_server.h"

namespace mavsdk {

using Position = LandingTargetServer::Position;




LandingTargetServer::LandingTargetServer(std::shared_ptr<ServerComponent> server_component) : ServerPluginBase(), _impl{std::make_unique<LandingTargetServerImpl>(server_component)} {}


LandingTargetServer::~LandingTargetServer() {}





LandingTargetServer::Result LandingTargetServer::publish_landing_target_relative(Position position) const
{
    return _impl->publish_landing_target_relative(position);
}



bool operator==(const LandingTargetServer::Position& lhs, const LandingTargetServer::Position& rhs)
{
    return
        ((std::isnan(rhs.x) && std::isnan(lhs.x)) || rhs.x == lhs.x) &&
        ((std::isnan(rhs.y) && std::isnan(lhs.y)) || rhs.y == lhs.y) &&
        ((std::isnan(rhs.z) && std::isnan(lhs.z)) || rhs.z == lhs.z);
}

std::ostream& operator<<(std::ostream& str, LandingTargetServer::Position const& position)
{
    str << std::setprecision(15);
    str << "position:" << '\n'
        << "{\n";
    str << "    x: " << position.x << '\n';
    str << "    y: " << position.y << '\n';
    str << "    z: " << position.z << '\n';
    str << '}';
    return str;
}



std::ostream& operator<<(std::ostream& str, LandingTargetServer::Result const& result)
{
    switch (result) {
        case LandingTargetServer::Result::Unknown:
            return str << "Unknown";
        case LandingTargetServer::Result::Success:
            return str << "Success";
        case LandingTargetServer::Result::NoSystem:
            return str << "No System";
        default:
            return str << "Unknown";
    }
}




} // namespace mavsdk