// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/precision_target/precision_target.proto)

#include <iomanip>

#include "precision_target_impl.h"
#include "plugins/precision_target/precision_target.h"

namespace mavsdk {

using PositionLocal = PrecisionTarget::PositionLocal;




PrecisionTarget::PrecisionTarget(System& system) : PluginBase(), _impl{std::make_unique<PrecisionTargetImpl>(system)} {}

PrecisionTarget::PrecisionTarget(std::shared_ptr<System> system) : PluginBase(), _impl{std::make_unique<PrecisionTargetImpl>(system)} {}


PrecisionTarget::~PrecisionTarget() {}





PrecisionTarget::Result PrecisionTarget::publish_position_relative(PositionLocal position_local) const
{
    return _impl->publish_position_relative(position_local);
}



bool operator==(const PrecisionTarget::PositionLocal& lhs, const PrecisionTarget::PositionLocal& rhs)
{
    return
        ((std::isnan(rhs.x) && std::isnan(lhs.x)) || rhs.x == lhs.x) &&
        ((std::isnan(rhs.y) && std::isnan(lhs.y)) || rhs.y == lhs.y) &&
        ((std::isnan(rhs.z) && std::isnan(lhs.z)) || rhs.z == lhs.z);
}

std::ostream& operator<<(std::ostream& str, PrecisionTarget::PositionLocal const& position_local)
{
    str << std::setprecision(15);
    str << "position_local:" << '\n'
        << "{\n";
    str << "    x: " << position_local.x << '\n';
    str << "    y: " << position_local.y << '\n';
    str << "    z: " << position_local.z << '\n';
    str << '}';
    return str;
}



std::ostream& operator<<(std::ostream& str, PrecisionTarget::Result const& result)
{
    switch (result) {
        case PrecisionTarget::Result::Unknown:
            return str << "Unknown";
        case PrecisionTarget::Result::Success:
            return str << "Success";
        case PrecisionTarget::Result::NoSystem:
            return str << "No System";
        default:
            return str << "Unknown";
    }
}




} // namespace mavsdk